server:
  port: 3000
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/mydb?useSSL=false
    username: root
    password: root
  thymeleaf:
    cache: false